[package]
name = "tmi-rs"
description = "Websocket based asynchronous connector to Twitch chat"
categories = ["asynchronous", "twitch", "websocket", "irc"]
keywords = ["twitch", "chat", "irc", "websockets", "async", "futures"]
version = "0.1.0"
authors = ["cerebellum42 <cere@fastmail.fm>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
log = "0.4.8"
fnv = "1.0.6"
derive_builder = "0.8.0"
derive_more = "0.15.0"
futures-core-preview = "0.3.0-alpha.19"
futures-sink-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
futures-channel-preview = { version = "0.3.0-alpha.19", features = ["sink"] }
pin-utils = "0.1.0-alpha.4"
tokio-io = "0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
tokio-net = "0.2.0-alpha.6"
tokio-tls = "0.3.0-alpha.6"
tokio-timer = "0.3.0-alpha.6"
tokio-tungstenite = { git = "https://github.com/dbcfd/tokio-tungstenite.git", rev = "0c2779965dc50b19256ef2d73edb82dd5db3e0de", features=["connect", "tls"] }
url = "2.1.0"
nom = "5.0.1"
smallvec = "0.6.10"
future-bus = "0.1.0"

[lib]
name = "tmi_rs"

[dev-dependencies]
env_logger = "0.7.1"
tokio = "0.2.0-alpha.6"
futures-preview = "0.3.0-alpha.19"
tokio-test = "0.2.0-alpha.6"